# Generated by Django 2.1.4 on 2018-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20181216_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='age_policy',
            field=models.IntegerField(null=True),
        ),
    ]
