# Generated by Django 2.1.4 on 2018-12-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20181216_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Текст, описывающий эту страницу'),
        ),
    ]
