# Generated by Django 2.1.4 on 2019-01-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_collectivepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectivepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
