# Generated by Django 2.1.8 on 2019-04-10 06:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_standardpage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Секция 1'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(blank=True, help_text='Заголовок Секция 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Секция 2'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(blank=True, help_text='Заголовок Секция 2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Секция 3'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section_3_title',
            field=models.CharField(blank=True, help_text='Заголовок Секция 3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(help_text='Подтекст на картинке', max_length=255, verbose_name='Подтекст на картинке'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Линк на промо страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Линк на промо страницу'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(help_text='Текст на картинке', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Картинка главной страницы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_image',
            field=models.ForeignKey(blank=True, help_text='Картинка промоблока', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Текст промо', null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo_title',
            field=models.CharField(blank=True, help_text='Заголовок промо', max_length=255, null=True),
        ),
    ]
