# Generated by Django 2.2.1 on 2019-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20190705_1748'),
        ('wagtailimages', '0001_squashed_0021'),
        ('base', '0023_auto_20190410_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('adress', models.CharField(max_length=254, verbose_name='Адрес')),
                ('link', models.CharField(max_length=254, verbose_name='Ссылка')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='job_title',
            field=models.CharField(max_length=254, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='SponsorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventPage')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Sponsor')),
            ],
        ),
    ]
