# Generated by Django 2.2.1 on 2019-07-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20190705_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorEvent',
        ),
    ]
