# Generated by Django 2.2.1 on 2019-07-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_sponsorevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='adress',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Ссылка'),
        ),
    ]
