# Generated by Django 2.2.1 on 2019-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20190709_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Категория'),
        ),
    ]
