# Generated by Django 2.2.1 on 2019-07-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_sponsor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Краткое описание(254 символа)'),
        ),
    ]
