# Generated by Django 2.2.6 on 2019-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='club_paid',
            field=models.BooleanField(default=False, help_text='Платный кружок'),
        ),
    ]
