# Generated by Django 2.2.6 on 2019-10-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_standardpage_club_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='club_paid',
        ),
        migrations.AddField(
            model_name='collectivepage',
            name='club_paid',
            field=models.BooleanField(default=False, help_text='Платный кружок'),
        ),
    ]
