# Generated by Django 2.2.6 on 2019-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20191027_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectivepage',
            name='club_paid',
            field=models.CharField(choices=[('paid_yes', 'Платные'), ('paid_no', 'Бесплатные')], default='paid_no', help_text='Платный кружок', max_length=255, verbose_name='Платный-Бесплатный'),
        ),
    ]
