# Generated by Django 2.2.6 on 2019-12-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0034_auto_20191027_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Секция 4'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_4_title',
            field=models.CharField(blank=True, help_text='Заголовок Секция 4', max_length=255, null=True),
        ),
    ]
