# Generated by Django 2.1.5 on 2020-05-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20191203_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypage',
            options={'ordering': ['-id']},
        ),
    ]
