# Generated by Django 2.2.6 on 2020-05-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20191203_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardpage',
            options={'ordering': ['-id']},
        ),
    ]
