# Generated by Django 2.1.5 on 2020-05-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200512_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypage',
            options={},
        ),
    ]
