# Generated by Django 2.2.6 on 2020-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200512_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardpage',
            options={},
        ),
        migrations.AlterField(
            model_name='collectivepage',
            name='club_paid',
            field=models.CharField(choices=[('paid_yes', 'Платный'), ('paid_no', 'Бесплатный'), ('volunteer', 'На общественных началах')], default='paid_no', help_text='Платный кружок', max_length=255, verbose_name='Платный-Бесплатный'),
        ),
    ]
