# Generated by Django 2.1.5 on 2020-05-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200526_1636'),
        ('base', '0037_auto_20200512_1508'),
    ]

    operations = [
    ]
