# Generated by Django 2.1.4 on 2018-12-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181220_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='age_policy',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='event_time',
        ),
    ]
