# Generated by Django 2.1.4 on 2018-12-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20181220_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='event_time',
        ),
    ]
