# Generated by Django 2.1.4 on 2018-12-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_eventpage_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
