# Generated by Django 2.1.4 on 2018-12-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventpage_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='event_time',
        ),
    ]
