# Generated by Django 2.1.4 on 2018-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20181220_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
