# Generated by Django 2.1.4 on 2018-12-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20181220_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='event_time',
        ),
    ]
