# Generated by Django 2.1.4 on 2018-12-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20181221_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
