# Generated by Django 2.2.1 on 2019-07-09 05:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import re


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_delete_sponsorevent'),
        ('event', '0013_auto_20190705_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='sponsors_list',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.CreateModel(
            name='EventSponsorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsor_relationship', to='event.EventPage')),
                ('sponsors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_event_relationship', to='base.People')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
