# Generated by Django 2.2.1 on 2019-07-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190709_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsponsorrelationship',
            name='sponsors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_event_relationship', to='base.Sponsor'),
        ),
    ]
