# Generated by Django 2.2.1 on 2019-07-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20190709_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='sponsors_list',
        ),
    ]
